# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(default='', max_length=50)),
                ('user_pic', models.ImageField(default='E:\\Study\\AppBlog\\AppBlog\\static\\upfile\\user\\icons\\default.jpg', height_field='url_height', upload_to='icons', width_field='url_width')),
                ('status', models.BooleanField(default=True)),
                ('level', models.IntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
