# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_pic',
            field=models.ImageField(default='E:\\Study\\AppBlog\\AppBlog\\static\\upfile\\user\\icons\\default.jpg', upload_to='icons'),
        ),
    ]
