# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
